name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to DockerHub
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: Build, push and tag gomxml-producer
      run: |
            docker build . --file producer.Dockerfile --tag kensobi/gomxml-producer:$(date +%s)
            docker push kensobi/gomxml-producer:$(date +%s)
            docker tag kensobi/gomxml-producer:$(date +%s) kensobi/gomxml-producer:latest    
   
